src/web/routes/clusters.py
"""Defines all routes related to clusters"""
import os

from flask import Blueprint, render_template
from sqlalchemy import create_engine, select
from src.utils.tables import clusters as clusters_table, faces as faces_table

blueprint = Blueprint('clusters', __name__, url_prefix='/clusters')

@blueprint.route("/")
def index():
    """
    Show an overview of all clusters in the database
    """
    db_engine = create_engine("sqlite:///" + os.environ["DATABASE_PATH"])
    with db_engine.connect() as conn:
        # Fetch all clusters and related faces
        query_clusters = (
            select(
                clusters_table.c.cluster_id,
                clusters_table.c.face_id,
                faces_table.c.file_id,
                faces_table.c.thumbnail_filename
            ).join(
                faces_table, clusters_table.c.face_id == faces_table.c.id
            ).order_by(clusters_table.c.cluster_id)
        )
        result_clusters = conn.execute(query_clusters)

        # Create a dictionary to group rows by cluster_id
        data_clusters = dict()

        # Iterate over the rows and append them to the appropriate group
        for row in result_clusters:
            # Use setdefault to initialize the list if the key does not exist
            data_clusters.setdefault(str(row.cluster_id), []).append({
                "face_id": row.face_id,
                "file_id": row.file_id,
                "thumbnail_path": "/files/thumbnails/" + row.thumbnail_filename
            })
        print(data_clusters)
        conn.close()
    return render_template(
        "clusters_overview.html", clusters=data_clusters
    )

src/web/routes/faces.py
"""Defines all routes related to faces"""
import os

from flask import Blueprint, render_template, request
from sqlalchemy import create_engine, select
from src.utils.tables import faces as faces_table, persons as persons_table

blueprint = Blueprint("faces", __name__, url_prefix='/faces')

@blueprint.route("/")
def index():
    """
    Show an overview of all faces in the database
    """
    db_engine = create_engine("sqlite:///" + os.environ["DATABASE_PATH"])
    with db_engine.connect() as conn:
        # Fetch all faces without a person_id
        query_faces = (
            select(
                faces_table.c.id,
                faces_table.c.thumbnail_filename,
                faces_table.c.person_id,
                faces_table.c.person_id_suggested,
                faces_table.c.file_id,
            )
            .where(faces_table.c.person_id.is_(None))
            .order_by(faces_table.c.person_id_suggested.desc())
        )
        result_faces = conn.execute(query_faces)

        data_faces = [
            {
                "thumbnail_path": "/files/thumbnails/" + row.thumbnail_filename
                if row.thumbnail_filename
                else None,
                "id": row.id,
                "person_id": row.person_id,
                "person_id_suggested": row.person_id_suggested,
                "file_id": row.file_id,
            }
            for row in result_faces
        ]

        # Fetch all persons
        query_persons = select(persons_table.c.id, persons_table.c.name)
        result_persons = conn.execute(query_persons)
        data_persons = [{"id": row.id, "name": row.name} for row in result_persons]
        conn.close()
    return render_template(
        "faces_overview.html", faces=data_faces, persons=data_persons
    )


@blueprint.route("/<int:face_id>", methods=["POST"])
def update_face(face_id):
    """
    Update an existing face record with a new person_id
    """
    data = request.json

    if not request.is_json:
        return "Invalid request, must be JSON", 415

    if (
        isinstance(data["person_id"], int)
        and face_id
        and isinstance(face_id, int)
    ):
        db_engine = create_engine("sqlite:///" + os.environ["DATABASE_PATH"])
        with db_engine.connect() as conn:
            # Update the face record with the new person_id
            update = (
                faces_table.update()
                .where(faces_table.c.id == face_id)
                .values(person_id=data["person_id"])
            )
            result = conn.execute(update)
            conn.commit()
            conn.close()

            if result.rowcount > 0:
                return "Face record updated successfully", 200

            return "Failed to update face record", 500

    return "Invalid request, missing (int)'person_id' and/or (int)'face_id' fields", 400

src/web/routes/files.py
"""Defines all routes related to files"""
import os

from flask import Blueprint, render_template, send_from_directory
from sqlalchemy import create_engine, select, outerjoin
from src.utils.tables import files as files_table, faces as faces_table

blueprint = Blueprint("files", __name__, url_prefix='/files')

@blueprint.route("/<int:file_id>")
def get_file(file_id):
    """
    Show the photo from the files table based on the id
    """
    db_engine = create_engine("sqlite:///" + os.environ["DATABASE_PATH"])
    with db_engine.connect() as conn:
        query_file = select(
            files_table.c.id,
            files_table.c.path,
            files_table.c.thumbnail_filename,
            files_table.c.last_updated,
            files_table.c.contains_face
        ).where(files_table.c.id == file_id)
        
        query_faces = select(
            faces_table.c.id,
            faces_table.c.facial_area_top,
            faces_table.c.facial_area_left,
            faces_table.c.facial_area_width,
            faces_table.c.facial_area_height
        ).where(faces_table.c.file_id == file_id)

        result_file = conn.execute(query_file).fetchone()
        result_faces = conn.execute(query_faces)
        data_faces = [{
            "id": row.id,
            "facial_area_top": row.facial_area_top,
            "facial_area_left": row.facial_area_left,
            "facial_area_width": row.facial_area_width,
            "facial_area_height": row.facial_area_height
        } for row in result_faces]
        conn.close()

    if result_file is None:
        return "File not found", 404
    else:
        return render_template(
            "file.html",
            file_id = result_file.id,
            file_path = result_file.path,
            thumbnail_path = "/files/thumbnails/" + result_file.thumbnail_filename,
            last_updated = result_file.last_updated,
            faces = data_faces
        )


@blueprint.route("/thumbnails/<path:filename>")
def thumbnail(filename):
    """
    Serve a thumbnail from the thumbnail folder
    """
    return send_from_directory(
        os.path.join("../../", os.environ["THUMBNAILS_PATH"]), filename
    )

src/web/routes/flows.py
"""Defines all routes related to controlling flows"""
from flask import Blueprint, render_template

blueprint = Blueprint('flows', __name__, url_prefix='/flows')

@blueprint.route("/")
def index():
    """
    Overview page
    """
    return render_template("base.html")

src/web/routes/persons.py
"""Defines all routes related to persons"""
import os

from flask import Blueprint, render_template, request
from sqlalchemy import create_engine, select, outerjoin
from src.utils.tables import faces as faces_table, persons as persons_table

blueprint = Blueprint('persons', __name__, url_prefix='/persons')

@blueprint.route("/")
def index():
    """
    Persons overview page
    """
    db_engine = create_engine("sqlite:///" + os.environ["DATABASE_PATH"])
    with db_engine.connect() as conn:
        # Select 1 face per person
        first_faces = select(
            faces_table.c.person_id,
            faces_table.c.thumbnail_filename
        ).where(faces_table.c.person_id.isnot(None)
        ).group_by(faces_table.c.person_id
        ).distinct(
        ).subquery()

        # Join persons_table with the first_faces subquery and exclude 'Ignored' which has ID 0
        query_persons = select(
            persons_table.c.id,
            persons_table.c.name,
            first_faces.c.thumbnail_filename
        ).select_from(
            outerjoin(persons_table, first_faces, persons_table.c.id == first_faces.c.person_id)
        ).where(persons_table.c.id > 0)

        result_persons = conn.execute(query_persons)
        data_persons = [{
            "id": row.id,
            "name": row.name,
            "thumbnail_path": "/files/thumbnails/" + row.thumbnail_filename
        } for row in result_persons]
        conn.close()

    return render_template("persons_overview.html", persons=data_persons)

@blueprint.route("/<int:person_id>")
def get_person(person_id):
    """
    Person page with all photos of this person
    """
    db_engine = create_engine("sqlite:///" + os.environ["DATABASE_PATH"])
    with db_engine.connect() as conn:
        query_faces = select(
            faces_table.c.id,
            faces_table.c.file_id,
            faces_table.c.thumbnail_filename,
            faces_table.c.facial_area_top,
            faces_table.c.facial_area_left,
            faces_table.c.facial_area_width,
            faces_table.c.facial_area_height,
        ).where(faces_table.c.person_id == person_id)
        
        query_persons = select(
            persons_table.c.name
        ).where(persons_table.c.id == person_id)

        result_faces = conn.execute(query_faces)
        result_persons = conn.execute(query_persons).fetchone()
        
        data_faces = [{
            "id": row.id,
            "file_id": row.file_id,
            "thumbnail_path": "/files/thumbnails/" + row.thumbnail_filename,
            "facial_area_top": row.facial_area_top,
            "facial_area_left": row.facial_area_left,
            "facial_area_width": row.facial_area_width,
            "facial_area_height": row.facial_area_height
        } for row in result_faces]
        conn.close()

    return render_template("person.html", name=result_persons.name, faces=data_faces)


@blueprint.route("/", methods=["POST"])
def add_person():
    """
    Add a new person to the database if it does not exist yet
    """
    data = request.json

    if not request.is_json:
        return "Invalid request, must be JSON", 415

    if data["name"]:
        db_engine = create_engine("sqlite:///" + os.environ["DATABASE_PATH"])
        with db_engine.connect() as conn:
            # Check if the person already exists
            query_person = select(persons_table).where(
                persons_table.c.name.collate("NOCASE") == data["name"].lower()
            )
            if conn.execute(query_person).fetchone():
                conn.close()
                return "Person already exists", 409

            # Otherwise, insert new person into the database
            insert_person = persons_table.insert().values(name=data["name"])
            result = conn.execute(insert_person)
            conn.commit()
            conn.close()

            if result.is_insert:
                return {"id": result.inserted_primary_key[0]}, 201

            return "Failed to insert person", 500

    return "Invalid request, missing 'name' field", 400

src/web/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>Tag My Photos</title>

    <link href="/static/tabler-1.0.0-beta20.min.css" rel="stylesheet"/>

    {% block style %}{% endblock %}

</head>
<body data-bs-theme="dark">
    
    <div class="sticky-top">
        <header class="navbar-expand-md">
            <div class="collapse navbar-collapse" id="navbar-menu">
              <div class="navbar">
                <div class="container-xl">
                  <ul class="navbar-nav">
                    <li class="nav-item {% if request.path == '/' %}active{% endif %}">
                      <a class="nav-link" href="{{ url_for('flows.index') }}" >
                        <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                          <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M5 12l-2 0l9 -9l9 9l-2 0" /><path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7" /><path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6" /></svg>
                        </span>
                        <span class="nav-link-title">
                          Overview
                        </span>
                      </a>
                    </li>
                    <li class="nav-item {% if request.path == '/faces' %}active{% endif %}">
                        <a class="nav-link" href="{{ url_for('faces.index') }}" >
                          <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/mood-empty -->
                            <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-mood-empty"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0" /><path d="M9 10l.01 0" /><path d="M15 10l.01 0" /><path d="M9 15l6 0" /></svg>
                          </span>
                          <span class="nav-link-title">
                            Tag Faces
                          </span>
                        </a>
                      </li>
                      <li class="nav-item {% if request.path == '/persons' %}active{% endif %}">
                        <a class="nav-link" href="{{ url_for('persons.index') }}" >
                          <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/user -->
                            <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-user"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M8 7a4 4 0 1 0 8 0a4 4 0 0 0 -8 0" /><path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" /></svg>
                          </span>
                          <span class="nav-link-title">
                            Persons
                          </span>
                        </a>
                      </li>
                      <li class="nav-item {% if request.path == '/clusters' %}active{% endif %}">
                        <a class="nav-link" href="{{ url_for('clusters.index') }}" >
                          <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/user -->
                            <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-user"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M8 7a4 4 0 1 0 8 0a4 4 0 0 0 -8 0" /><path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" /></svg>
                          </span>
                          <span class="nav-link-title">
                            Unknown Similar Faces
                          </span>
                        </a>
                      </li>
                  </ul>
                </div>
            </div>
            </div>
        </header>

    </div>
    
    {% block content %}{% endblock %}

    <script src="/static/tabler-1.0.0-beta20.min.js" defer></script>
    {% block scripts %}{% endblock %}
</body>
    

src/web/templates/clusters_overview.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    {% for cluster in clusters %}
      <h2>Cluster {{ cluster }}</h2>
      <div class="row">
        {% for face in clusters[cluster] %}
          <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 face-container">
            <figure class="figure rounded overflow-hidden position-relative"> 
              <a href="{{ url_for('files.get_file', file_id=face.file_id) }}">
                <img src="{{ face.thumbnail_path }}" class="figure-img img-fluid">
              </a>
              <figcaption class="figure-caption">
                <form class="tag-person-form">
                    <div class="row g-2">
                      <div class="col">
                        FaceID: {{ face.face_id }}
                        <input name="face_id" type="hidden" value="{{ face.face_id }}">
                      </div>
                      <div class="col-auto">
                        <input type="submit" class="btn" value="Save" />
                      </div>
                    </div>
                </form>
              </figcaption>
            </figure>
          </div>
        {% endfor %}
      </div>
    {% endfor %}
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <ul class="pagination ">
            <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1" aria-disabled="true">
                <!-- Download SVG icon from http://tabler-icons.io/i/chevron-left -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M15 6l-6 6l6 6"></path></svg>
                prev
              </a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item active"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">4</a></li>
            <li class="page-item"><a class="page-link" href="#">5</a></li>
            <li class="page-item">
              <a class="page-link" href="#">
                next <!-- Download SVG icon from http://tabler-icons.io/i/chevron-right -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M9 6l6 6l-6 6"></path></svg>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block style %}
  <style>
    .figure {
      width: 100%;
    }

    .figure-img {
      margin-bottom: 0;
      width: 100%;
    }

    .figure-caption {
      position: absolute;
      bottom: 0;
      width: 100%;
      background: rgba(0, 0, 0, 0.3);
      color: white;
      padding: 10px 15px;
    }
  </style>
{% endblock %}

src/web/templates/faces_overview.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row">
      {% for face in faces %}
        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 face-container">
          <figure class="figure rounded overflow-hidden position-relative"> 
            <a href="{{ url_for('files.get_file', file_id=face.file_id) }}">
              <img src="{{ face.thumbnail_path }}" class="figure-img img-fluid">
            </a>
            <figcaption class="figure-caption">
              <form class="tag-person-form">
                  <div class="row g-2">
                    <div class="col">
                      <input name="person" class="form-control" list="persons" {% if face.person_id_suggested %}value="{{ persons | selectattr('id', 'eq', face.person_id_suggested) | map(attribute='name') | first }}" {% endif %} placeholder="Type to add a name..." autocapitalize="on" translate="no" autocomplete="off">
                      <input name="face_id" type="hidden" value="{{ face.id }}">
                    </div>
                    <div class="col-auto">
                      <input type="submit" class="btn" value="Save" />
                    </div>
                  </div>
              </form>
            </figcaption>
          </figure>
        </div>
      {% endfor %}
    </div>
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <ul class="pagination ">
            <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1" aria-disabled="true">
                <!-- Download SVG icon from http://tabler-icons.io/i/chevron-left -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M15 6l-6 6l6 6"></path></svg>
                prev
              </a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item active"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">4</a></li>
            <li class="page-item"><a class="page-link" href="#">5</a></li>
            <li class="page-item">
              <a class="page-link" href="#">
                next <!-- Download SVG icon from http://tabler-icons.io/i/chevron-right -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M9 6l6 6l-6 6"></path></svg>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <datalist id="persons">
    {% for person in persons %}
      <option value="{{ person.name }}"></option>
    {% endfor %}
  </datalist>
{% endblock %}

{% block style %}
  <style>
    .figure {
      width: 100%;
    }

    .figure-img {
      margin-bottom: 0;
      width: 100%;
    }

    .figure-caption {
      position: absolute;
      bottom: 0;
      width: 100%;
      background: rgba(0, 0, 0, 0.3);
      color: white;
      padding: 10px 15px;
    }
  </style>
{% endblock %}

{% block scripts %}
  <script>
    // Note: must be single-quoted since Jinja inserts JSON with double quotes
    let personsJson = '{{ persons | tojson }}';
    let persons = JSON.parse(personsJson) || [];

    // Handle Face Tagging Form: check if the person already exists, if not add a new person, and add it to the face
    document.querySelectorAll('.tag-person-form').forEach(form => {
      form.addEventListener('submit', async (event) => {
        event.preventDefault();
        const formData = new FormData(event.target);
        const person = formData.get('person');
        let person_id = null;

        // Prevent empty input
        if (!person || person.trim() === ''){
          return;
        }

        // If we don't know the person yet, add it to the database first
        const personExists = persons.find((p) => p.name.toLowerCase() === person.toLowerCase());

        if (!personExists) {
          const person_response = await fetch('/persons', {
            method: 'POST',
            body: JSON.stringify({ name: person }),
            headers: { 'Content-Type': 'application/json' }
          });

          if (person_response.status === 201) {
            data = await person_response.json();
            person_id = data.id;

            // Add the new person to the persons list for local lookup
            persons.push({ id: person_id, name: person });
            document.getElementById('persons').innerHTML += `<option value="${person}"></option>`;
          } else {
            console.log('Error creating person', await person_response.text());
            // TODO: Show error message to user
          }
        // Or fetch it locally if we can find it in the persons list
        } else {
          person_id = personExists.id;
        }

        // Update the Face record with the defined person_id
        const faceId = formData.get('face_id');
        const face_response = await fetch(`/faces/${faceId}`, {
          method: 'POST',
          body: JSON.stringify({ person_id: person_id }),
          headers: { 'Content-Type': 'application/json' }
        });

        if (face_response.status === 200) {
          console.log(`Face ${faceId} updated successfully with Person ID ${person_id}`)
          // Hide the face container after tagging
          parent = event.explicitOriginalTarget.parentElement.closest('.face-container').style.display = 'none';
        } else {
          console.log('Error updating face person_id', await face_response.text());
          // TODO: Show error message to user
        }
      })
    });
  </script>
{% endblock %}

src/web/templates/person.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h1>{{ name }}</h1>
    <div class="row">
      {% for face in faces %}
        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 face-container">
          <figure class="figure rounded overflow-hidden position-relative"> 
            <a href="{{ url_for('files.get_file', file_id=face.file_id) }}">
              <img src="{{ face.thumbnail_path }}" class="figure-img img-fluid">
            </a>
          </figure>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

{% block style %}
  <style>
    .figure {
      width: 100%;
    }

    .figure-img {
      margin-bottom: 0;
      width: 100%;
    }

    .figure-caption {
      position: absolute;
      bottom: 0;
      width: 100%;
      background: rgba(0, 0, 0, 0.3);
      color: white;
      padding: 10px 15px;
    }
  </style>
{% endblock %}

src/web/templates/persons_overview.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row">
      {% for person in persons %}
        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 face-container">
          <figure class="figure rounded overflow-hidden position-relative"> 
            <a href="{{ url_for('persons.get_person', person_id=person.id) }}">
              <img src="{{ person.thumbnail_path }}" class="figure-img img-fluid">
            </a>
            <figcaption class="figure-caption">
              <div class="row g-2">
                <div class="col">
                  {{ person.name }}
                </div>
              </div>
            </figcaption>
          </figure>
        </div>
      {% endfor %}
    </div>
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <ul class="pagination ">
            <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1" aria-disabled="true">
                <!-- Download SVG icon from http://tabler-icons.io/i/chevron-left -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M15 6l-6 6l6 6"></path></svg>
                prev
              </a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item active"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">4</a></li>
            <li class="page-item"><a class="page-link" href="#">5</a></li>
            <li class="page-item">
              <a class="page-link" href="#">
                next <!-- Download SVG icon from http://tabler-icons.io/i/chevron-right -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M9 6l6 6l-6 6"></path></svg>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block style %}
  <style>
    .figure {
      width: 100%;
    }

    .figure-img {
      margin-bottom: 0;
      width: 100%;
    }

    .figure-caption {
      position: absolute;
      bottom: 0;
      width: 100%;
      background: rgba(0, 0, 0, 0.3);
      color: white;
      padding: 10px 15px;
    }
  </style>
{% endblock %}

{% block scripts %}
  <script>
    // Note: must be single-quoted since Jinja inserts JSON with double quotes
    let personsJson = '{{ persons | tojson }}';
    let persons = JSON.parse(personsJson) || [];

    // Handle Face Tagging Form: check if the person already exists, if not add a new person, and add it to the face
    document.querySelectorAll('.tag-person-form').forEach(form => {
      form.addEventListener('submit', async (event) => {
        event.preventDefault();
        const formData = new FormData(event.target);
        const person = formData.get('person');
        let person_id = null;

        // Prevent empty input
        if (!person || person.trim() === ''){
          return;
        }

        // If we don't know the person yet, add it to the database first
        const personExists = persons.find((p) => p.name.toLowerCase() === person.toLowerCase());

        if (!personExists) {
          const person_response = await fetch('/person', {
            method: 'POST',
            body: JSON.stringify({ name: person }),
            headers: { 'Content-Type': 'application/json' }
          });

          if (person_response.status === 201) {
            data = await person_response.json();
            person_id = data.id;

            // Add the new person to the persons list for local lookup
            persons.push({ id: person_id, name: person });
            document.getElementById('persons').innerHTML += `<option value="${person}"></option>`;
          } else {
            console.log('Error creating person', await person_response.text());
            // TODO: Show error message to user
          }
        // Or fetch it locally if we can find it in the persons list
        } else {
          person_id = personExists.id;
        }

        // Update the Face record with the defined person_id
        const faceId = formData.get('face_id');
        const face_response = await fetch(`/face/${faceId}`, {
          method: 'POST',
          body: JSON.stringify({ person_id: person_id }),
          headers: { 'Content-Type': 'application/json' }
        });

        if (face_response.status === 200) {
          console.log(`Face ${faceId} updated successfully with Person ID ${person_id}`)
          // Hide the face container after tagging
          parent = event.explicitOriginalTarget.parentElement.closest('.face-container').style.display = 'none';
        } else {
          console.log('Error updating face person_id', await face_response.text());
          // TODO: Show error message to user
        }
      })
    });
  </script>
{% endblock %}